pipeline {
    agent {
        dockerfile {
            dir '.ci'
            label 'docker-executor'
        }
    }

    options {
        withAWS(
            endpointUrl: 'https://storage.kevinlin.info',
            credentials: 'storage-internal',
        )
    }

    stages {
        stage('Environment') {
            steps {
                s3Download(
                    bucket: 'internal',
                    path: 'resources/linkr/config/options/client.json',
                    file: 'config/options/client.json',
                )
                s3Download(
                    bucket: 'internal',
                    path: 'resources/linkr/config/options/server.json',
                    file: 'config/options/server.json',
                )
                s3Download(
                    bucket: 'internal',
                    path: 'resources/linkr/config/secrets/client.json',
                    file: 'config/secrets/client.json',
                )
                s3Download(
                    bucket: 'internal',
                    path: 'resources/linkr/config/secrets/server.json',
                    file: 'config/secrets/server.json',
                )
            }
        }
        stage('Install') {
            parallel {
                stage('Python') {
                    steps {
                        sh 'virtualenv --always-copy env'
                        sh '. env/bin/activate && pip install -r requirements.txt'
                    }
                }
                stage('Node') {
                    steps {
                        sh 'npm-s3 install'
                    }
                }
            }
        }
        stage('Frontend') {
            parallel {
                stage('Lint') {
                    steps {
                        sh 'npm run lint-frontend'
                    }
                }
                stage('Test') {
                    steps {
                        sh 'npm run test-frontend'
                    }
                }
                stage('Build') {
                    steps {
                        sh '. env/bin/activate && npm run build'
                    }
                }
            }
        }
        stage('Backend') {
            parallel {
                stage('Lint') {
                    steps {
                        sh '. env/bin/activate && npm run lint-backend'
                    }
                }
                stage('Test') {
                    steps {
                        sh '. env/bin/activate && npm run test-backend'
                    }
                }
            }
        }
        stage('Release') {
            steps {
                sh 'virtualenv --relocatable env'
                sh 'tar -czf release.tar.gz *'
                s3Upload(
                    bucket: 'internal',
                    path: "deploy/${env.JOB_NAME}/${env.GIT_COMMIT}/",
                    file: 'release.tar.gz',
                )
            }
        }
    }
}
